apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: kic
  name: kic-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - keeping-it-casual.com
        - test.keeping-it-casual.com
        - test.api.keeping-it-casual.com
        - api.keeping-it-casual.com
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: istio-svcs-certs
      hosts:
        - keeping-it-casual.com
        - test.keeping-it-casual.com
        - api.keeping-it-casual.com
        - test.api.keeping-it-casual.com
    - port:
        number: 50051
        name: grpc
        protocol: GRPC
      hosts:
        - "*"